// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/cluster.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClusterTestMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterTestMessage) Reset()         { *m = ClusterTestMessage{} }
func (m *ClusterTestMessage) String() string { return proto.CompactTextString(m) }
func (*ClusterTestMessage) ProtoMessage()    {}
func (*ClusterTestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_4163bc58eee10ea9, []int{0}
}
func (m *ClusterTestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterTestMessage.Unmarshal(m, b)
}
func (m *ClusterTestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterTestMessage.Marshal(b, m, deterministic)
}
func (dst *ClusterTestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterTestMessage.Merge(dst, src)
}
func (m *ClusterTestMessage) XXX_Size() int {
	return xxx_messageInfo_ClusterTestMessage.Size(m)
}
func (m *ClusterTestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterTestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterTestMessage proto.InternalMessageInfo

func (m *ClusterTestMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ClusterTestMessage)(nil), "messages.ClusterTestMessage")
}

func init() { proto.RegisterFile("messages/cluster.proto", fileDescriptor_cluster_4163bc58eee10ea9) }

var fileDescriptor_cluster_4163bc58eee10ea9 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x89, 0x2b, 0xe9, 0x71, 0x09, 0x39, 0x43, 0xa4, 0x42, 0x52, 0x8b,
	0x4b, 0x7c, 0x21, 0xc2, 0x42, 0x12, 0x5c, 0xec, 0x50, 0x15, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x00, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x7d,
	0x51, 0x71, 0x5a, 0x00, 0x00, 0x00,
}
