// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package network

import "sync"

type Uint64MessageChanSyncMap struct {
	inner sync.Map
}

func (m *Uint64MessageChanSyncMap) Store(k uint64, v MessageChan) {
	m.inner.Store(k, v)
}

func (m *Uint64MessageChanSyncMap) Load(k uint64) (MessageChan, bool) {
	val, ok := m.inner.Load(k)
	if !ok {
		return nil, false
	}

	return val.(MessageChan), true
}

func (m *Uint64MessageChanSyncMap) Range(cb func(uint64, MessageChan) bool) {
	m.inner.Range(func(k interface{}, v interface{}) bool {
		return cb(k.(uint64), v.(MessageChan))
	})
}

func (m *Uint64MessageChanSyncMap) Delete(key uint64) {
	m.inner.Delete(key)
}
