// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package network

import "sync"

type StringMessageProcessorSyncMap struct {
	inner sync.Map
}

func (m *StringMessageProcessorSyncMap) Store(k string, v MessageProcessor) {
	m.inner.Store(k, v)
}

func (m *StringMessageProcessorSyncMap) Load(k string) (MessageProcessor, bool) {
	val, ok := m.inner.Load(k)
	if !ok {
		return nil, false
	}

	return val.(MessageProcessor), true
}

func (m *StringMessageProcessorSyncMap) Range(cb func(string, MessageProcessor) bool) {
	m.inner.Range(func(k interface{}, v interface{}) bool {
		return cb(k.(string), v.(MessageProcessor))
	})
}

func (m *StringMessageProcessorSyncMap) Delete(key string) {
	m.inner.Delete(key)
}
