// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package network

import "sync"

type StringPluginInterfaceSyncMap struct {
	inner sync.Map
}

func (m *StringPluginInterfaceSyncMap) Store(k string, v PluginInterface) {
	m.inner.Store(k, v)
}

func (m *StringPluginInterfaceSyncMap) Load(k string) (PluginInterface, bool) {
	val, ok := m.inner.Load(k)
	if !ok {
		return nil, false
	}

	return val.(PluginInterface), true
}

func (m *StringPluginInterfaceSyncMap) Range(cb func(string, PluginInterface) bool) {
	m.inner.Range(func(k interface{}, v interface{}) bool {
		return cb(k.(string), v.(PluginInterface))
	})
}

func (m *StringPluginInterfaceSyncMap) Delete(key string) {
	m.inner.Delete(key)
}
