// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/stream.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ID) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Message struct {
	Message *any.Any `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Sender's address and public key.
	Sender *ID `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Sender's signature of message.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Nonce is the request/response ID. Null if ID associated to a message is not a request/response.
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetSender() *ID {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{2}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{3}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type LookupNodeRequest struct {
	Target               *ID      `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupNodeRequest) Reset()         { *m = LookupNodeRequest{} }
func (m *LookupNodeRequest) String() string { return proto.CompactTextString(m) }
func (*LookupNodeRequest) ProtoMessage()    {}
func (*LookupNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{4}
}
func (m *LookupNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupNodeRequest.Unmarshal(m, b)
}
func (m *LookupNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupNodeRequest.Marshal(b, m, deterministic)
}
func (dst *LookupNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupNodeRequest.Merge(dst, src)
}
func (m *LookupNodeRequest) XXX_Size() int {
	return xxx_messageInfo_LookupNodeRequest.Size(m)
}
func (m *LookupNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupNodeRequest proto.InternalMessageInfo

func (m *LookupNodeRequest) GetTarget() *ID {
	if m != nil {
		return m.Target
	}
	return nil
}

type LookupNodeResponse struct {
	Peers                []*ID    `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupNodeResponse) Reset()         { *m = LookupNodeResponse{} }
func (m *LookupNodeResponse) String() string { return proto.CompactTextString(m) }
func (*LookupNodeResponse) ProtoMessage()    {}
func (*LookupNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{5}
}
func (m *LookupNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupNodeResponse.Unmarshal(m, b)
}
func (m *LookupNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupNodeResponse.Marshal(b, m, deterministic)
}
func (dst *LookupNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupNodeResponse.Merge(dst, src)
}
func (m *LookupNodeResponse) XXX_Size() int {
	return xxx_messageInfo_LookupNodeResponse.Size(m)
}
func (m *LookupNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupNodeResponse proto.InternalMessageInfo

func (m *LookupNodeResponse) GetPeers() []*ID {
	if m != nil {
		return m.Peers
	}
	return nil
}

type StreamPacket struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamPacket) Reset()         { *m = StreamPacket{} }
func (m *StreamPacket) String() string { return proto.CompactTextString(m) }
func (*StreamPacket) ProtoMessage()    {}
func (*StreamPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_809e88eeeb7f3d52, []int{6}
}
func (m *StreamPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamPacket.Unmarshal(m, b)
}
func (m *StreamPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamPacket.Marshal(b, m, deterministic)
}
func (dst *StreamPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPacket.Merge(dst, src)
}
func (m *StreamPacket) XXX_Size() int {
	return xxx_messageInfo_StreamPacket.Size(m)
}
func (m *StreamPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPacket.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPacket proto.InternalMessageInfo

func (m *StreamPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ID)(nil), "protobuf.ID")
	proto.RegisterType((*Message)(nil), "protobuf.Message")
	proto.RegisterType((*Ping)(nil), "protobuf.Ping")
	proto.RegisterType((*Pong)(nil), "protobuf.Pong")
	proto.RegisterType((*LookupNodeRequest)(nil), "protobuf.LookupNodeRequest")
	proto.RegisterType((*LookupNodeResponse)(nil), "protobuf.LookupNodeResponse")
	proto.RegisterType((*StreamPacket)(nil), "protobuf.StreamPacket")
}

func init() { proto.RegisterFile("protobuf/stream.proto", fileDescriptor_stream_809e88eeeb7f3d52) }

var fileDescriptor_stream_809e88eeeb7f3d52 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4f, 0x4f, 0x2a, 0x31,
	0x10, 0x4f, 0x61, 0x81, 0xc7, 0xc0, 0xe5, 0x35, 0xbc, 0x97, 0xd5, 0x68, 0xb2, 0x69, 0x8c, 0xe1,
	0x54, 0x12, 0xbc, 0xe8, 0xc1, 0x83, 0x84, 0x0b, 0x51, 0xc9, 0x66, 0xfd, 0x00, 0xa6, 0xb0, 0x63,
	0xb3, 0x01, 0xda, 0xb5, 0xed, 0x1e, 0xf6, 0x73, 0xf8, 0x85, 0x0d, 0xed, 0x2e, 0x1a, 0x3d, 0x75,
	0x7e, 0x7f, 0x66, 0x7e, 0x93, 0x29, 0xfc, 0x2b, 0x8d, 0x76, 0x7a, 0x53, 0xbd, 0xcd, 0xac, 0x33,
	0x28, 0x0e, 0xdc, 0x63, 0xfa, 0xa7, 0xa5, 0xcf, 0xcf, 0xa4, 0xd6, 0x72, 0x8f, 0xb3, 0x93, 0x4f,
	0xa8, 0x3a, 0x98, 0xd8, 0x3d, 0x74, 0x56, 0x4b, 0x7a, 0x09, 0x50, 0x56, 0x9b, 0x7d, 0xb1, 0x7d,
	0xdd, 0x61, 0x1d, 0x93, 0x84, 0x4c, 0xc7, 0xd9, 0x30, 0x30, 0x8f, 0x58, 0xd3, 0x18, 0x06, 0x22,
	0xcf, 0x0d, 0x5a, 0x1b, 0x77, 0x12, 0x32, 0x1d, 0x66, 0x2d, 0x64, 0x1f, 0x04, 0x06, 0xcf, 0x68,
	0xad, 0x90, 0x48, 0x39, 0x0c, 0x0e, 0xa1, 0xf4, 0x13, 0x46, 0xf3, 0x09, 0x0f, 0xb9, 0xbc, 0xcd,
	0xe5, 0x0f, 0xaa, 0xce, 0x5a, 0x13, 0xbd, 0x82, 0xbe, 0x45, 0x95, 0xa3, 0xf1, 0x43, 0x47, 0xf3,
	0xf1, 0x97, 0x6f, 0xb5, 0xcc, 0x1a, 0x8d, 0x5e, 0xc0, 0xd0, 0x16, 0x52, 0x09, 0x57, 0x19, 0x8c,
	0xbb, 0x61, 0xb3, 0x13, 0x41, 0x27, 0xd0, 0x53, 0x5a, 0x6d, 0x31, 0x8e, 0x12, 0x32, 0x8d, 0xb2,
	0x00, 0x58, 0x1f, 0xa2, 0xb4, 0x50, 0xd2, 0xbf, 0x5a, 0x49, 0x76, 0x07, 0x7f, 0x9f, 0xb4, 0xde,
	0x55, 0xe5, 0x5a, 0xe7, 0x98, 0xe1, 0x7b, 0x85, 0xd6, 0x1d, 0xe3, 0x9d, 0x30, 0x12, 0x5d, 0xb3,
	0xed, 0x8f, 0xf8, 0xa0, 0xb1, 0x5b, 0xa0, 0xdf, 0x5b, 0x6d, 0xa9, 0x95, 0x45, 0xca, 0xa0, 0x57,
	0x22, 0x1a, 0x1b, 0x93, 0xa4, 0xfb, 0xab, 0x35, 0x48, 0x8c, 0xc1, 0xf8, 0xc5, 0x7f, 0x47, 0x2a,
	0xb6, 0x3b, 0x74, 0x94, 0x42, 0x94, 0x0b, 0x27, 0x9a, 0xeb, 0xfa, 0x7a, 0x71, 0x0d, 0xff, 0xb5,
	0x91, 0xbc, 0x44, 0xb3, 0x2f, 0x14, 0x57, 0xba, 0xb0, 0xcd, 0xb1, 0x16, 0xb0, 0x3e, 0x82, 0xf4,
	0x58, 0xa7, 0x64, 0xd3, 0xf7, 0xe4, 0xcd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x9f, 0x46,
	0x97, 0xea, 0x01, 0x00, 0x00,
}
